feeds.sync.allowed-users=${FEED_SYNC_ALLOWED_USERS}

# Choose between memory and jdbc implementations
repository.type=${REPOSITORY_TYPE}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
