apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: auth-server
  name: keycloak-configmap
data:
  KC_CACHE: ispn
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME: <Gateway-URL>/auth
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY_HEADERS: xforwarded
