services:
  db:
    image: postgres:17-alpine
    container_name: feeder-db
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - feeder_db_data:/var/lib/postgresql/data

volumes:
  feeder_db_data: